### ISSUE TITLE
Add RPLACA and RPLACD

### ISSUE THREAD

**Issue by oubiwann** [lfex/cl#12]

**Comment by rvirding** [comment]
These are impossible in LFE as they are supposed to mutate the cons cell which, of course we can't do on the BEAM.

**Comment by oubiwann** [comment]
I was thinking about doing this with immutable data, adjusting for a non-side-effect version with LFE. More for the fun of it than anything. 

I had imagined the usage to be something like this:

``` cl
> (rplaca (one two three . four) 'uno)
(uno two three . four)
> (rplacd (cddr *some-list*) (list 'iv))
(uno two three iv)
```

What do you think?

**Comment by rvirding** [comment]
Then they are more or less just a `cons`. No I would say that generally do it properly, i.e. according to the manual, or not at all. In this case it might be confusing if someone expects it to behave like in CL but it silently doesn't.

**Comment by oubiwann** [comment]
Sounds like a great approach. That answers the other question I had about cl:nth -- we'll do zero-based lists for cl, since that's what in the CLHS.

Thanks!
